#!/usr/bin/env python3

"""
  remove_inline.py: A script that takes as stdin-input an rfc822 compliant
  message and gives as stdout-output the same message, but with all inline
  parts (those with a 'Content-Disposition: inline' MIME part, such as
  embedded logos and other inline images) removed. Non-inline (regular)
  attachments and the main body parts are left untouched.

  Copyright (C) 2026 Erik Quaeghebeur

  This program is free software: you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version. This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  details. You should have received a copy of the GNU General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
"""

import sys
import email
import email.policy


# Check whether no arguments have been given to the script (it takes none)
nargs = len(sys.argv)
if len(sys.argv) != 1:
    raise SyntaxError(f"This script takes no arguments, you gave {nargs - 1}.")

# define email policy
email_policy = email.policy.EmailPolicy(
    max_line_length=None, linesep="\r\n", refold_source="none"
)

# Read and parse the message from stdin
msg = email.message_from_bytes(sys.stdin.buffer.read(), policy=email_policy)


def prune_inline(container):
    """Recursively drop inline-disposition child parts of a multipart
    container, leaving everything else (in particular non-inline
    attachments and the parts making up the displayed body) untouched."""
    if not container.is_multipart():
        return
    kept = []
    for part in container.get_payload():
        if part.is_multipart():
            prune_inline(part)
            kept.append(part)
        elif part.get_content_disposition() == "inline":
            continue  # drop this inline part
        else:
            kept.append(part)
    container.set_payload(kept)


# Remove inline parts throughout the message
prune_inline(msg)

# Check whether no errors were found in the message (parts)
if any(len(part.defects) > 0 for part in msg.walk()):
    raise Exception("An error occurred.")

# Send the modified message to stdout
sys.stdout.buffer.write(msg.as_bytes(policy=email_policy))
